---
output: github_document
bibliography: doc/student_performance_refs.bib
---

# DSCI522 Group 403 - Student Performance Predictors

Investigating the predictors of Portuguese high school student performance

This project is proudly brought to you by:

- [Brayden Tang](https://github.com/braydentang1)
- [Kenneth Foo](https://github.com/kfoofw)
- [Brendon Campbell](https://github.com/brendoncampbell)

## Introduction

For this project we are trying to answer the question: what are the top five features that most strongly predict high school student's performances in their Portuguese language course? To do so we are working with a UCI Machine Learning Repository [@CortezUCI] data set which can be found [here](https://archive.ics.uci.edu/ml/datasets/Student+Performance), which includes student grades for two subjects (Math and Portuguese), demographic, social and other school related features.

We conduct exploratory data analysis, fit and tune several predictive models, compare their performance, then report and comment on the most predictive features from the best model. Our final report can be found [here.](doc/student_performance_report.md)

## Usage

To replicate the analysis, clone this GitHub repository, install the [dependencies](#dependencies) listed below, and run the following commands at the command line/terminal from the root directory of this project:

```
python src/download_data.py --out_type=feather --url=http://mlr.cs.umass.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data --out_file=data/raw/wdbc.feather
Rscript -e "rmarkdown::render('src/breast_cancer_eda.Rmd')"
```

## Dependencies
- Python 3.7.3 [@Python] and Python packages: 
  - docopt==0.6.2 [@docoptpython]
  - pytest==5.3.4 [@pytest]
  - bayesian-optimization==1.01 [@bayesopt]
  - altair==3.2.0 [@Altair2018]
  - pandas==0.25.3 [@mckinney2010data]
  - scikit-learn==0.22.1 [@sklearn_api]
  - numpy==1.17.4 [@oliphant2006guide]
  - xgboost==0.90 [@Chen:2016:XST:2939672.2939785]
  - lightgbm==2.3.0 [@Ke2017LightGBMAH]

- R version 3.6.1 [@R] and R packages:
  - docopt==0.6.1 [@docopt]
  - knitr==1.26 [@knitr]
  - tidyverse==1.2.1 [@tidyverse]
  - caret==6.0-85 [@caret]
  - ggridges==0.5.2 [@ggridges]
  - ggcorrplot==0.1.3 [@ggcorrplot]
  - testthat==2.2.1 [@testthat]
  
## License
The Student Performance Predictors materials here are licensed under the Creative Commons Attribution 2.5 Canada License (CC BY 2.5 CA). If re-using/re-mixing please provide attribution and link to this webpage.

# References